Revert "explict implementation of '__hash__' attr in BaseNetref"
This reverts commit bd8b56060596427d0d5a880b2a39fee3a0515d20.

It turns out this commit breaks hashing netrefs for classes:

    >>> c = rpyc.classic.connect("localhost")

    >>> hash(c.modules.numpy.array([0]).__class__)
    ...
    TypeError: 'NoneType' object is not callable

    >>> hash(c.modules.numpy.array([0]).__class__.__mro__[1])
    TypeError: descriptor '__hash__' of 'object' object needs an argument